import React from "react";

function UserMyPosts() {



    const getUserPosts = async() => {
        // Url for user will be implemented in the future
        url = "http://"
        response = await fetch(url)
    }


    return (
        <div className="max-h-full px-8 py-6 overflow-y-auto">
            <p>UserMyPosts</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa reiciendis possimus enim doloribus non dicta neque aliquam labore fugit earum tempora amet repellendus debitis ab sed, magni deserunt eius aspernatur temporibus, hic, voluptate repellat asperiores. Eos ratione nihil totam officiis, nam sint incidunt deleniti, dolorem, facere animi ea molestias nemo error laudantium? Eaque nostrum architecto nam incidunt, eveniet error id harum exercitationem sint, tempore, maxime distinctio. Autem, sed distinctio quibusdam aliquam tempore facere labore voluptates recusandae, accusantium illum laboriosam magnam officia perferendis quas ea, laborum animi. Deleniti natus, quo cumque fuga hic obcaecati veritatis ea, laudantium, quae velit id repellat!</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa reiciendis possimus enim doloribus non dicta neque aliquam labore fugit earum tempora amet repellendus debitis ab sed, magni deserunt eius aspernatur temporibus, hic, voluptate repellat asperiores. Eos ratione nihil totam officiis, nam sint incidunt deleniti, dolorem, facere animi ea molestias nemo error laudantium? Eaque nostrum architecto nam incidunt, eveniet error id harum exercitationem sint, tempore, maxime distinctio. Autem, sed distinctio quibusdam aliquam tempore facere labore voluptates recusandae, accusantium illum laboriosam magnam officia perferendis quas ea, laborum animi. Deleniti natus, quo cumque fuga hic obcaecati veritatis ea, laudantium, quae velit id repellat!</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa reiciendis possimus enim doloribus non dicta neque aliquam labore fugit earum tempora amet repellendus debitis ab sed, magni deserunt eius aspernatur temporibus, hic, voluptate repellat asperiores. Eos ratione nihil totam officiis, nam sint incidunt deleniti, dolorem, facere animi ea molestias nemo error laudantium? Eaque nostrum architecto nam incidunt, eveniet error id harum exercitationem sint, tempore, maxime distinctio. Autem, sed distinctio quibusdam aliquam tempore facere labore voluptates recusandae, accusantium illum laboriosam magnam officia perferendis quas ea, laborum animi. Deleniti natus, quo cumque fuga hic obcaecati veritatis ea, laudantium, quae velit id repellat!</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa reiciendis possimus enim doloribus non dicta neque aliquam labore fugit earum tempora amet repellendus debitis ab sed, magni deserunt eius aspernatur temporibus, hic, voluptate repellat asperiores. Eos ratione nihil totam officiis, nam sint incidunt deleniti, dolorem, facere animi ea molestias nemo error laudantium? Eaque nostrum architecto nam incidunt, eveniet error id harum exercitationem sint, tempore, maxime distinctio. Autem, sed distinctio quibusdam aliquam tempore facere labore voluptates recusandae, accusantium illum laboriosam magnam officia perferendis quas ea, laborum animi. Deleniti natus, quo cumque fuga hic obcaecati veritatis ea, laudantium, quae velit id repellat!</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa reiciendis possimus enim doloribus non dicta neque aliquam labore fugit earum tempora amet repellendus debitis ab sed, magni deserunt eius aspernatur temporibus, hic, voluptate repellat asperiores. Eos ratione nihil totam officiis, nam sint incidunt deleniti, dolorem, facere animi ea molestias nemo error laudantium? Eaque nostrum architecto nam incidunt, eveniet error id harum exercitationem sint, tempore, maxime distinctio. Autem, sed distinctio quibusdam aliquam tempore facere labore voluptates recusandae, accusantium illum laboriosam magnam officia perferendis quas ea, laborum animi. Deleniti natus, quo cumque fuga hic obcaecati veritatis ea, laudantium, quae velit id repellat!</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa reiciendis possimus enim doloribus non dicta neque aliquam labore fugit earum tempora amet repellendus debitis ab sed, magni deserunt eius aspernatur temporibus, hic, voluptate repellat asperiores. Eos ratione nihil totam officiis, nam sint incidunt deleniti, dolorem, facere animi ea molestias nemo error laudantium? Eaque nostrum architecto nam incidunt, eveniet error id harum exercitationem sint, tempore, maxime distinctio. Autem, sed distinctio quibusdam aliquam tempore facere labore voluptates recusandae, accusantium illum laboriosam magnam officia perferendis quas ea, laborum animi. Deleniti natus, quo cumque fuga hic obcaecati veritatis ea, laudantium, quae velit id repellat!</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa reiciendis possimus enim doloribus non dicta neque aliquam labore fugit earum tempora amet repellendus debitis ab sed, magni deserunt eius aspernatur temporibus, hic, voluptate repellat asperiores. Eos ratione nihil totam officiis, nam sint incidunt deleniti, dolorem, facere animi ea molestias nemo error laudantium? Eaque nostrum architecto nam incidunt, eveniet error id harum exercitationem sint, tempore, maxime distinctio. Autem, sed distinctio quibusdam aliquam tempore facere labore voluptates recusandae, accusantium illum laboriosam magnam officia perferendis quas ea, laborum animi. Deleniti natus, quo cumque fuga hic obcaecati veritatis ea, laudantium, quae velit id repellat!</p>
        </div>
    );
}

export default UserMyPosts;
